//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int MID { get; set; }
        public string MName { get; set; }
        public string MUrl { get; set; }
        public Nullable<System.DateTime> MTime { get; set; }
        public Nullable<int> UNum { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
