        //------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeFirst开发方式
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.Chinese = 0D;
            this.English = 0D;
            this.IT = 0D;
        }
    
        public int ID { get; set; }
        public double Chinese { get; set; }
        public double English { get; set; }
        public double IT { get; set; }
        public int InfoID { get; set; }
    
        public virtual Info Info { get; set; }
    }
}
